### ISSUE TITLE
Reload tab on double click? (suggestion)

### ISSUE THREAD

**Issue by Toms29** [pylorak/reloadmatic#12]
Since the Reload tab on double click add-on is not compatible with the new FF and there's still no replacement, can you consider in adding this option to ReloadMatic? 
It would help to a lot of people.

Thank you.

**Comment by pylorak** [comment]
Nice idea! I'd like to add support for this, let me check what options I have and I will get back to you here.

**Comment by Toms29** [comment]
Thanks a lot!

I have another problem with POST, I enabled it on purpose and then it sending to this link:
https://cdn.iubenda.com/cookie_solution/iframe_bridge.html?origin=https%3A%2F%2Fsubeta.net%2Fshop.php&meth=%22compact%22

with the message 405 Not Allowed

Can it be fixed? I'm playing a virtual pet site so I'm auto-refreshing to do some quick actions..

**Comment by pylorak** [comment]
Hi! Unfortunately Firefox does not allow addons to react to double-clicking on a tab header, so it is not possible for any plugin to implement it. Double-clicking on page contents could be used, but that collides with word-selection, so that is not a good idea.

About subeta: Can you please provide the URL of the page that you are trying to refresh instead of the wrong page you are being forwarded to? The latter is not useful for me to diagnose.

**Comment by Toms29** [comment]
Sorry for the late reply!

Will it ever be allowed it in the future? it seems the extensions change is only limiting the extensions freedom..  
There has to be a way of a quick refreshing, the double click was great because it was very quick to move to the tab instead to the refresh button

about Subeta, it's this page
https://subeta.net/shop.php?shopid=19
you'll have to register and to buy an item from the shop and then to use ReloadMatic to understand the problem.

**Comment by pylorak** [comment]
I don't know if it'll ever be allowed in the future. You need to ask that question to Mozilla.
To quickly refresh a page, you can still use F5 or CTRL+R.

As for subeta, you need to provide me a URL that I can test without buying things from the internet. Just how do you suppose I test otherwise? If you have such an URL (no buying things and no registration), please open a separate issue.
