### ISSUE TITLE
Favicon indicator

### ISSUE THREAD

**Issue by xuhcc** [pylorak/reloadmatic#17]
Is it possible to show indicator on auto-reloading tabs in a way TabMix Plus does?

![screenshot from 2017-12-10 19-30-10](https://user-images.githubusercontent.com/1660460/33807042-eaee5df2-dde1-11e7-8e66-2406c88707d5.png)

**Comment by pbarquei** [comment]
Or a counter (indicator) such as Reload Plus?

**Comment by pylorak** [comment]
Hello,
 TabMix Plus could do this because it is a legacy extension. Since Firefox 57 only new-style extensions (WebExtensions) are allowed and it is not yet possible to add indicators or badges with WebExtensions.  I've already tried raising an issue to Mozilla about this (see Bug [1420361)](https://bugzilla.mozilla.org/show_bug.cgi?id=1420361), but it looks like it is not just a problem of the plugin framework, but now Firefox as a whole misses this feature. So to get this functionality to plugins, we must first get Mozilla to implement it.

**Comment by pylorak** [comment]
Hi! As a workaround to the missing feature in Firefox, ReloadMatic now sets a badge in the tab header by inserting a graphical character into the page's title. I hope you'll like this and the other improvements in the new version :)

**Comment by xuhcc** [comment]
@pylorak Thanks!

But unfortunately, this doesn't work with pinned tabs.

**Comment by pylorak** [comment]
I know, but there is nothing that can be done about it in the current state of Firefox. If it ever becomes possible for WebExtensions, I'll migrate to real icon badges.
