### ISSUE TITLE
Doesn't remember page scroll position, 2nd try

### ISSUE THREAD

**Issue by esquien** [pylorak/reloadmatic#19]
12/15/17  9am EDT in NJ

This previous issue with 1.5.0 was announced as fixed by an enhancement in 1.5.1 5 days ago.

It sadly wasn't and a new, additional error was added by 1.5.1

Pylorak, I emailed you full details with attachments on 12/10/17 - maybe you didn't get the email.
I just "replied" to an email I got from you.

So, here with slight edits I have re-presented the problem. So everyone can be aware.   Cheers,  QE

Using Firefox Quantum 57.0.2  and reloadmatic 1.5.1.  Win 7 Pro.

My daily use requires me to frequently reload whilst scrolling down the page increasing amounts.

If I use the Firefox curly arrow to reload the page scroll position is remembered.

reloadmatic doesn't remember same. it's reloaded pg always starts at the top.  

TIA, esquien

**Comment by pylorak** [comment]
Hi, sorry I didn't answer earlier. I saw your previous reply I'm just preoccupied these days with work and also private life due to the nearing holiday season, so until things settle down (after the holidays) ReloadMatic will have to wait. 

In my tests 1.5.1 remembers scroll position, the difference to native firefox reload is that native reload scrolls to the final position already while the page is still loading because it remembers the page layout, whereas ReloadMatic will only scroll once the page has fully loaded. I will do some experiments to see if if I can scroll earlier, but since I need to give scroll coordinates to firefox in pixels, the scroll position will only be exact if both the page layout and all contents (including also images and any and all media) have loaded.

**Comment by esquien** [comment]
Thanks for your answer.   In my old-school programming ignorance I just figured that FF's "API" would give you a simple call to do a FF-like reload.   Anyway, ReloadMatic is still helping me -  I'm using 1.5.0 and one extra click.

Merry Christmas to you and your family.  Cheers,  QE in NJ USA

**Comment by pylorak** [comment]
Hi esquien!
Please try updating to 1.5.2 now. It contains a fix related to caches always being disabled even when they shouldn't. It turns out out this is why "FF-like" reload/scrolling didn't work, so scrolling behavior is now the same as native reload for GET pages. POST pages still use the custom logic for scrolling or else there is no way to control the warning popup by the browser.
