### ISSUE TITLE
frums and sticky reload

### ISSUE THREAD

**Issue by gooly** [pylorak/reloadmatic#8]
Hi,
I am watching e.g. this forum: [https://www.mql5.com/en/forum](url)
On this page I watch whether a new post was made, and if so I enter this post and may I answer it - then I go back again to the forum.
Now the sticky-option keeps reloading the forum after I got back to it (fine!!) but as well when I entered a post and while I read it or while I try to answer it.
I'd like and I have seen that previously that if I leave the form-page and enter a single post the automatic reload is not present, but when I got back to the forum this page is (still, again) reloaded automatically every ...
That was pretty convenient as before the automatic reload has eliminated once and a while what I have written.

**Comment by pylorak** [comment]
Your problem is just about to be solved. In version 1.5.0 you will be able to set remembered pages. When you revisit a remembered page, the settings for that page will be restored and activated, even without sticky reload.

Should be released in a few hours, or if something comes up, tomorrow.

**Comment by pylorak** [comment]
Hi, I have released version 1.5 and now you can make ReloadMatic remember reload settings for individual pages. You would disable Sticky Reload and enable Remember Page on the forum listing, so that whenever you go back to it, it will keep reloading, but not while writing a post. Let me know if it works for you.
